---
- name: Delete a specific file on Windows Server
  hosts: 10.1.44.125
  gather_facts: no
  tasks:
    - name: Delete file C:\Temp\delete.txt
      win_file:
        path: C:\Temp\delete.txt
        state: absent
